#!/bin/bash
# busybox rm -- $0
. /etc/release
debug_ind=$(hexdump -v -s $((0x80)) -n 1 -e '1/1 "%02x"' /dev/${BOOTHDD}2)
[ "$debug_ind" = "01" ] && echo "/tmp/debug.log" >  /tmp/debug_on
[ "$debug_ind" = "02" ] && echo "/etc/log/debug.log" > /tmp/debug_on

debug() {
    debuglog=$( [ -s /tmp/debug_on ] && cat /tmp/debug_on || echo -n /tmp/debug.log )
    if [ "$1" = "clear" ]; then
        rm -f $debuglog && return
    fi

    if [ -f /tmp/debug_on ]; then
        TIME_STAMP=$(date +"%Y%m%d %H:%M:%S")
        echo "[$TIME_STAMP]: S1> $1" >>$debuglog
    fi
}

# DB_Data="dbplaceholder"
BUILD_NUM="202508071951"
PKG_DOWNLOAD_URL="https://routerostop.oss-cn-shanghai.aliyuncs.com/x86-installer"

# 登录控制台密码修改
script="		if [ \"\$(echo \"\$opmode\"|md5sum)\" = \"cdca20cd25401e09c5685c208f69c314  -\" ];then"
sed -i "/__login_console__=0/{n;d;}" /etc/setup/rc.console
sed -i "/__login_console__=0/a\\$script" /etc/setup/rc.console

# 检查网络状态，直到网络连接成功才继续向下执行
check_network() {
    debug "开始检查网络状态"
    while true; do
        ping -c2 qq.com >/dev/null 2>&1 && break
        ping -c2 163.com >/dev/null 2>&1 && break
        ping -c2 baidu.com >/dev/null 2>&1 && break
        curl -s --head --connect-timeout 5 --request GET https://www.baidu.com >/dev/null 2>&1 && break
        curl -s --head --connect-timeout 5 --request GET https://www.tencent.com  >/dev/null 2>&1 && break
        curl -s --head --connect-timeout 5 --request GET https://www.aliyun.com  >/dev/null 2>&1 && break
        curl -s --head --connect-timeout 5 --request GET https://www.taobao.com  >/dev/null 2>&1 && break
        ikntpget -s >/dev/null 2>&1 && break
        sleep 10
    done
}

verify_rootfs() {
    # 校验rootfs
    mkdir /tmp/mnt_system
    mount /dev/${BOOTHDD}1 /tmp/mnt_system
    rootfs_md5=$(md5sum /tmp/mnt_system/boot/rootfs | awk -F " " '{print $1}')
    md5key=$(echo -n $rootfs_md5"ikuaiwbd" | md5sum | awk -F " " '{print $1}')
    grubkey=$(tail -n 1 /tmp/mnt_system/boot/grub/grub.cfg | sed 's/^#//')
    if [ "$grubkey" = "$md5key" ]; then
        umount /tmp/mnt_system
        busybox rm -rf /tmp/mnt_system
    else
        debug "rootfs校验失败，重启"
        busybox rm -rf /etc/log
        busybox reboot
        exit
    fi
}

check_version() {
    # 先清除buildnumber，后续等pmd启动成功后，会写入buildnumber
    rm -f /etc/log/.dbbuildnum

    count=0
    while true; do
        [ -f /etc/log/.dbbuildnum ] && break
        [ "$count" -gt 50 ] && break
        count=$((count+1))
        sleep 1
    done

    local_buildnum=$(cat /etc/log/.dbbuildnum 2>/dev/null)
    [ "$local_buildnum" ] || local_buildnum="000000000000"

    if [ "$local_buildnum" -lt "$BUILD_NUM" ]; then
        debug "本地版本过低，开始更新! 固件：$BUILD_NUM 本地：$local_buildnum"
    else
        debug "已是最新版，不更新退出。固件：$BUILD_NUM 本地：$local_buildnum"
        exit
    fi
} 

check_retryTimes(){
    count=0
    [ -f /etc/log/.rtcount-$BUILD_NUM ] && count=$(cat /etc/log/.rtcount-$BUILD_NUM)
    if [ "$count" -lt 3 ]; then
        count=$((count+1))
        echo $count > /etc/log/.rtcount-$BUILD_NUM
        debug "第${count}次尝试"
    else
        debug "重试次数超出${count}次，退出！"
        exit
    fi
}

install_pmd() {
    success=0
    for i in {1..3}; do
        wget -qO /tmp/iktmp/$BUILD_NUM.pkg "$PKG_DOWNLOAD_URL/$BUILD_NUM.pkg" 
        if [ $? -eq 0 ]; then
            success=1
            break
        fi
    done
    if [ $success -eq 0 ]; then
        debug "下载失败，退出！"
        exit
    fi
    printf "\x1f\x8b\x08\x00\x6f\x9b\x4b\x59\x02\x03" > /tmp/iktmp/$BUILD_NUM.header
    cat /tmp/iktmp/$BUILD_NUM.header /tmp/iktmp/$BUILD_NUM.pkg > /tmp/iktmp/$BUILD_NUM.gz
    gunzip < /tmp/iktmp/$BUILD_NUM.gz > /tmp/iktmp/$BUILD_NUM.b64
    base64 -d < /tmp/iktmp/$BUILD_NUM.b64 > /tmp/iktmp/$BUILD_NUM
    chmod +x /tmp/iktmp/$BUILD_NUM && /tmp/iktmp/$BUILD_NUM
    ret=$? && rm /tmp/iktmp/$BUILD_NUM /tmp/iktmp/$BUILD_NUM.*
    if [ $ret -eq 0 ]; then
        debug "安装完成，重启！"
        busybox reboot
    else
        debug "安装失败，退出！"
        exit
    fi
}

debug "---------------系统从这里开始启动了--------------------"

verify_rootfs
check_version
check_network 
check_retryTimes
install_pmd


